### ISSUE TITLE
problem after installation.

### ISSUE THREAD

**Issue by arounderor** [Limmen/csle#443]
There is no content in table "config" after installation. After insert from csle/config.json manually, error occurs when start emulation, which show that container has no ip in gw bridge.

I want to know which step in "Manual Installation" insert data to config table? Thanks very much.

Futhermore, is CSLE compatible for WSL? I met a lot of problems according to postgres.

FIRST
(py311) user@DESKTOP:~/csle/metastore$ csle ls --all
Successfully initialized configuration from configuration file: /home/user/csle/config.json
CSLE cluster:
Uncaught exception
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/py311/bin/csle", line 7, in <module>
    sys.exit(commands())
             ^^^^^^^^^^
  File "/home/user/miniconda3/envs/py311/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/py311/lib/python3.11/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/py311/lib/python3.11/site-packages/click/core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/py311/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/py311/lib/python3.11/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/py311/lib/python3.11/site-packages/csle_cli/cli.py", line 3463, in ls
    list_all(all=all, running=running, stopped=stopped)
  File "/home/user/miniconda3/envs/py311/lib/python3.11/site-packages/csle_cli/cli.py", line 4301, in list_all
    list_cluster()
  File "/home/user/miniconda3/envs/py311/lib/python3.11/site-packages/csle_cli/cli.py", line 4665, in list_cluster
    for node in config.cluster_config.cluster_nodes:
                ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cluster_config'

SECOND

user@DESKTOP:~/csle/metastore$ csle start csle-level9-080 Successfully initialized configuration from configuration file: /home/user/csle/config.json Starting emulation csle-level9-080 The specified execution ID: None is not valid or is already taken. Using ID: 28 instead -- Step 1/41: Starting containers -- -- Starting containers of emulation: csle-level9-080 on server: 172.25.169.17-- -- Step 2/41: Creating networks for emulation: csle-level9-080 -- -- Step 3/41: Connect containers to networks -- -- Connecting containers of: emulation csle-level9-080 to networks on server: 172.25.169.17-- Uncaught exception Traceback (most recent call last): File "/home/user/anaconda3/bin/csle", line 8, in <module> sys.exit(commands()) File "/home/user/anaconda3/lib/python3.9/site-packages/click/core.py", line 1161, in __call__ return self.main(*args, **kwargs) File "/home/user/anaconda3/lib/python3.9/site-packages/click/core.py", line 1082, in main rv = self.invoke(ctx) File "/home/user/anaconda3/lib/python3.9/site-packages/click/core.py", line 1697, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/user/anaconda3/lib/python3.9/site-packages/click/core.py", line 1443, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/user/anaconda3/lib/python3.9/site-packages/click/core.py", line 788, in invoke return __callback(*args, **kwargs) File "/home/user/csle/simulation-system/libs/csle-cli/src/csle_cli/cli.py", line 2150, in start run_emulation(emulation_env_config, no_traffic=no_traffic, no_clients=no_clients, id=id, File "/home/user/csle/simulation-system/libs/csle-cli/src/csle_cli/cli.py", line 469, in run_emulation ClusterController.run_emulation(execution=execution, no_traffic=no_traffic, no_clients=no_clients, File "/home/user/csle/simulation-system/libs/csle-cluster/src/csle_cluster/cluster_manager/cluster_controller.py", line 3675, in run_emulation ClusterController.attach_containers_in_execution_to_networks( File "/home/user/csle/simulation-system/libs/csle-cluster/src/csle_cluster/cluster_manager/cluster_controller.py", line 58, in attach_containers_in_execution_to_networks csle_cluster.cluster_manager.query_cluster_manager.attach_containers_in_execution_to_networks( File "/home/user/csle/simulation-system/libs/csle-cluster/src/csle_cluster/cluster_manager/query_cluster_manager.py", line 609, in attach_containers_in_execution_to_networks stub.attachContainersInExecutionToNetworks(operation_msg, timeout=timeout) File "/home/user/anaconda3/lib/python3.9/site-packages/grpc/_channel.py", line 1178, in __call__ return _end_unary_response_blocking(state, call, False, None) File "/home/user/anaconda3/lib/python3.9/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking raise _InactiveRpcError(state) # pytype: disable=not-instantiable grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with: status = StatusCode.UNKNOWN details = "Exception calling application: The container with id:a1f616e4388306e66a6c1b2828efa67567b11712a8f22485f652790d97172012 does not have an IP in the docker gw bridge network. Containers: {'34380d6da7070e659c9d8326ab33f6a79b8756c6ebbde85d302b831d636f15cc': {'Name': 'csle_client_1_1-level9-26', 'EndpointID': '1078c33679a5f64e1593cbf38653fb45f09406c35eb13c69f867e7fb97455916', 'MacAddress': '0e:32:fc:d5:2e:3e', 'IPv4Address': '172.18.0.4/16', 'IPv6Address': ''}, '512e7a6889c25339e81d65c5583c6b09398afd7ce1b5da9f299fca87d5025a32': {'Name': 'csle_client_1_1-level9-24', 'EndpointID': '8d79e59c7a63d3a717085ee7307bf3aa5fdd00fad1c5897f54cf0fb18332cc1c', 'MacAddress': '32:24:4b:60:b4:9f', 'IPv4Address': '172.18.0.5/16', 'IPv6Address': ''}, '78fe744975eb36d6d27e2d8fa2436341b6501d62b0513d917ccd47be28ec0fc6': {'Name': 'csle_client_1_1-level9-25', 'EndpointID': '58de53d73c6e1571a45230a01e4511507f1196c30f64b10c2d006342c254add0', 'MacAddress': 'c6:e6:a4:cd:46:d5', 'IPv4Address': '172.18.0.3/16', 'IPv6Address': ''}, 'b7e0f1d20dad70f33c3c8e6776119105da58cb78ab9f1722a174a8f15381bb7f': {'Name': 'csle_client_1_1-level9-23', 'EndpointID': 'c4af036c01feca17f285b0c25acdce2f58ad08ec7d1bf83aafe1035c55f92682', 'MacAddress': '6a:8e:b3:d8:13:17', 'IPv4Address': '172.18.0.6/16', 'IPv6Address': ''}, 'ingress-sbox': {'Name': 'gateway_ingress-sbox', 'EndpointID': 'b174e55f86b4928239efa4048c41a4cf8fd61286df5844c8932a9fc1edaa69b8', 'MacAddress': 'a6:d0:08:b6:02:e7', 'IPv4Address': '172.18.0.2/16', 'IPv6Address': ''}}" debug_error_string = "UNKNOWN:Error received from peer {grpc_status:2, grpc_message:"Exception calling application: The container with id:a1f616e4388306e66a6c1b2828efa67567b11712a8f22485f652790d97172012 does not have an IP in the docker gw bridge network. Containers: {\'34380d6da7070e659c9d8326ab33f6a79b8756c6ebbde85d302b831d636f15cc\': {\'Name\': \'csle_client_1_1-level9-26\', \'EndpointID\': \'1078c33679a5f64e1593cbf38653fb45f09406c35eb13c69f867e7fb97455916\', \'MacAddress\': \'0e:32:fc:d5:2e:3e\', \'IPv4Address\': \'172.18.0.4/16\', \'IPv6Address\': \'\'}, \'512e7a6889c25339e81d65c5583c6b09398afd7ce1b5da9f299fca87d5025a32\': {\'Name\': \'csle_client_1_1-level9-24\', \'EndpointID\': \'8d79e59c7a63d3a717085ee7307bf3aa5fdd00fad1c5897f54cf0fb18332cc1c\', \'MacAddress\': \'32:24:4b:60:b4:9f\', \'IPv4Address\': \'172.18.0.5/16\', \'IPv6Address\': \'\'}, \'78fe744975eb36d6d27e2d8fa2436341b6501d62b0513d917ccd47be28ec0fc6\': {\'Name\': \'csle_client_1_1-level9-25\', \'EndpointID\': \'58de53d73c6e1571a45230a01e4511507f1196c30f64b10c2d006342c254add0\', \'MacAddress\': \'c6:e6:a4:cd:46:d5\', \'IPv4Address\': \'172.18.0.3/16\', \'IPv6Address\': \'\'}, \'b7e0f1d20dad70f33c3c8e6776119105da58cb78ab9f1722a174a8f15381bb7f\': {\'Name\': \'csle_client_1_1-level9-23\', \'EndpointID\': \'c4af036c01feca17f285b0c25acdce2f58ad08ec7d1bf83aafe1035c55f92682\', \'MacAddress\': \'6a:8e:b3:d8:13:17\', \'IPv4Address\': \'172.18.0.6/16\', \'IPv6Address\': \'\'}, \'ingress-sbox\': {\'Name\': \'gateway_ingress-sbox\', \'EndpointID\': \'b174e55f86b4928239efa4048c41a4cf8fd61286df5844c8932a9fc1edaa69b8\', \'MacAddress\': \'a6:d0:08:b6:02:e7\', \'IPv4Address\': \'172.18.0.2/16\', \'IPv6Address\': \'\'}}"}" >

**Comment by Limmen** [comment]
Hi @arounderor , the config table is updated when you run "csle init" you can debug it from 
- https://github.com/Limmen/csle/blob/master/simulation-system/libs/csle-cli/src/csle_cli/cli.py#L39 and 
- https://github.com/Limmen/csle/blob/master/simulation-system/libs/csle-common/src/csle_common/util/cluster_util.py#L30

**Comment by Limmen** [comment]
Regarding WSL, I have never tried it, so I am not sure. The main concern I have is whether Linux containers are supported in WSL? If they are supported then I think it should be possible.

**Comment by Limmen** [comment]
I don't have experience with configuring a proxy for the containers, unfortunately.

**Comment by arounderor** [comment]
Thank you so much, I have successfully started an emulation.
But when I ran "csle start managementsystem", I got "name: managementsystem not recognized". 
I also tried "management_system" and I don't find similar phrase in "simulation-system/libs/csle-cli/src/csle_cli/cli.py" start function.

By the way, I'd like to point out that in [the csle document, ](https://limmen.dev/csle/docs/quick-start/), "csle start nodeexporter" should be "csle start node_exporter";
in https://limmen.dev/csle/docs/installing/, "git clone https://github.com/Limmen/clse" should be "csle".

**Comment by Limmen** [comment]
Nice, I will get back to development and make a new release with updated documentation soon. 

It should be "csle start flask" instead of "csle start managementsystem". If you want to make a contribution, you can modify here and open a PR:
https://github.com/Limmen/csle/blob/master/docs/_docs/quick_start.md?plain=1#L40

Similarly, https://github.com/Limmen/csle/blob/master/docs/_docs/installing.md?plain=1#L50

Otherwise I will update it as soon as I have time.

**Comment by Limmen** [comment]
Try running python server.py in management system/ https://github.com/Limmen/csle/blob/master/management-system/csle-mgmt-webapp/server/server.py

I think there is some python library missing

**Comment by Limmen** [comment]
Ok if you see the Not found it means that the flask server is running but it is not serving the JavaScript correctly. It is supposed to just serve the static files here: https://github.com/Limmen/csle/blob/master/management-system/csle-mgmt-webapp/server/server.py#L4. You can add a print here to check which folder the server is started in and then make sure the static-folder path matches to your build folder: https://github.com/Limmen/csle/blob/master/simulation-system/libs/csle-rest-api/src/csle_rest_api/rest_api.py#L312

**Comment by arounderor** [comment]
I was able to access the static web page after running server.py, but csle start flask doesn’t seem to work. When I tried to debug, I ran into a lot of gRPC-related code.
The part of this project that excites me most is the link between the emulation and simulation environments. Could you give me some advice on how to gain a deeper understanding of this connection, so that to show the trained agent has actually learned from real-world-like scenarios and can be deployed to protect a live network?
Thank you very much for your patience and help.

**Comment by NNNNelson** [comment]
> I was able to access the static web page after running server.py, but csle start flask doesn’t seem to work. When I tried to debug, I ran into a lot of gRPC-related code. The part of this project that excites me most is the link between the emulation and simulation environments. Could you give me some advice on how to gain a deeper understanding of this connection, so that to show the trained agent has actually learned from real-world-like scenarios and can be deployed to protect a live network? Thank you very much for your patience and help.

Hello, How did you fix this issue? “AttributeError: 'NoneType' object has no attribute 'cluster_config'
”

**Comment by Limmen** [comment]
Hi @NNNNelson, ok when you run csle init is there some error log?

**Comment by NNNNelson** [comment]
Thank you for your response. Below is the log I encountered
(py311) kim@kim-virtual-machine:~/csle$ csle init
Successfully initialized configuration from configuration file: /home/kim/csle//config.json
nohup: redirecting stderr to stdout
